creation_rules:
  - path_regex: '.*values\.yaml$'
    pgp: "724F500945BCC137625A3673CF957C48EDCBEA5D"
  - path_regex: '.*\.yaml$'
    pgp: "724F500945BCC137625A3673CF957C48EDCBEA5D"
    encrypted_regex: ^(data|stringData)$