creation_rules:
  - path_regex: '.*values\.yaml$'
    age: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
  - path_regex: '.*\.yaml$'
    age: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
    encrypted_regex: ^(data|stringData)$