apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: paperless-pg-monitor
  labels:
    app.kubernetes.io/part-of: paperless
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - paperless
  selector:
    matchExpressions:
      - key: "cnpg.io/cluster"
        operator: In
        values:
          - paperless-pg
  podMetricsEndpoints:
    - port: metrics