apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-pg
  annotations:
    k8up.io/backup: "false"
spec:
  instances: 2

  bootstrap:
    initdb:
      database: paperless_ngx
      owner: paperless-ngx
      secret:
        name: pg-secret

#    recovery:
#      source: origin
#      database: paperless-ngx
#      owner: paperless-ngx
#      secret:
#        name: pg-secret

#  externalClusters:
#    - name: origin
#      plugin:
#        name: barman-cloud.cloudnative-pg.io
#        parameters:
#          barmanObjectName: backup-store-dr
#          serverName: paperless-pg

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backup-store

  storage:
    size: 4Gi
  monitoring:
    enablePodMonitor: true
