apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-pg
spec:
  instances: 2
  affinity:
    nodeSelector:
      kubernetes.io/hostname: homelab-leader
  bootstrap:
    recovery:
      source: origin

  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: backup-store
          serverName: paperless-pg

#  plugins:
#    - name: barman-cloud.cloudnative-pg.io
#      isWALArchiver: true
#      parameters:
#        barmanObjectName: backup-store

  storage:
    size: 6Gi
    storageClass: local-path
  monitoring:
    enablePodMonitor: true
