apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-pg
spec:
  instances: 2
  affinity:
    nodeSelector:
      kubernetes.io/hostname: homelab-leader
  bootstrap:
    initdb:
      database: paperless_ngx
      owner: paperless-ngx
      secret:
        name: pg-secret
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backup-store
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
