apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: memogram
    app.kubernetes.io/name: memogram
    app.kubernetes.io/version: 0.3.0
  name: memogram
  namespace: memos
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: memogram
      app.kubernetes.io/name: memogram
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: memogram
        app.kubernetes.io/name: memogram
    spec:
      automountServiceAccountToken: true
      containers:
        - env:
            - name: SERVER_ADDR
              value: memos:5230
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: bot-token
                  name: memogram-secret
          image: twaslowski/memogram:canary
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "pgrep -f memogram > /dev/null"
            failureThreshold: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: memogram
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
