apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: memos
spec:
  interval: 15m
  chart:
    spec:
      chart: memos
      version: "0.17.0"
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: flux-system
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: memos-values