image:
  repository: twaslowski/memos
  tag: "canary"
  pullPolicy: Always

env:
  TZ: "Europe/Berlin"
  MEMOS_DRIVER: "postgres"
  MEMOS_INSTANCE_URL: "https://memos.twaslowski.com"
  MEMOS_DSN:
    valueFrom:
      secretKeyRef:
        name: pg-secret
        key: uri

controller:
  strategy: RollingUpdate

ingress:
  main:
    enabled: true
    ingressClassName: "cloudflare-tunnel"
    hosts:
      - host: memos.twaslowski.com
        paths:
          - path: /
            pathType: Prefix
            service:
              port: 5230

persistence:
  data:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
