apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - release.yaml
  - podmonitor.yaml
configMapGenerator:
  - name: kube-state-metrics-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml