apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kube-state-metrics
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchExpressions:
      - key: "app.kubernetes.io/name"
        operator: In
        values:
          - kube-state-metrics
  podMetricsEndpoints:
    - port: http