apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: grammr-prod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: grammr-core
    namespace: flux-system
  policy:
    semver:
      range: "3.x"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: update-grammr-core-prod
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1m
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(grammr): automated image update
    push:
      branch: main
  update:
    path: ./apps/homelab/grammr/overlays/prod/core/values.yaml
    strategy: Setters
