apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: "6.30.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: loki-values