---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: paperless-file-backup
  namespace: paperless-ngx
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: rclone-backup
            image: rclone/rclone:1.67

            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-creds
                    key: aws_access_key_id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-creds
                    key: aws_secret_access_key
              - name: AWS_REGION
                value: "eu-central-1"
              - name: S3_BUCKET
                value: "246770851643-eu-central-1-homelab-cluster-storage"

              - name: DIRECTORY
                value: "/paperless/data"
              - name: TARGET_DIR
                value: "backups/paperless-ngx/files/data"

            command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Starting paperless-ngx backup at $(date)"
              
              # Configure rclone for S3
              mkdir -p /root/.config/rclone
              cat > /root/.config/rclone/rclone.conf << EOF
              [s3]
              type = s3
              provider = AWS
              access_key_id = ${AWS_ACCESS_KEY_ID}
              secret_access_key = ${AWS_SECRET_ACCESS_KEY}
              region = ${AWS_REGION}
              EOF
              
              echo "Syncing ${DIRECTORY} to s3://${S3_BUCKET}/${TARGET_DIR}"
              rclone sync /paperless/export s3:${S3_BUCKET}/${TARGET_DIR} \
                --transfers 4 \
                --checkers 8 \
                --progress \
                --stats 30s \
                --exclude "*.tmp" \
                --exclude "*.temp"
              
              echo "Backup completed successfully for directory ${DIRECTORY}"

            volumeMounts:
            - name: paperless-data
              mountPath: /paperless/data
              readOnly: false

            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"

          volumes:
          - name: paperless-data
            persistentVolumeClaim:
              claimName: paperless-ngx-data
