apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: paperless-values
    files:
      - values.yaml=values.yaml
secretGenerator:
  - name: core-values-secret
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml