apiVersion: v1
kind: Secret
metadata:
    name: pg-secret
    namespace: vaultwarden
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: vaultwarden
    password: ENC[AES256_GCM,data:RmUpGZHmaTI32ieFY/UbyWQ1RbSkaKQ=,iv:YJeaci7A2kefcpwg3JJP3ArwW8y/TAsgG8AivElFpmA=,tag:/PiqO47sdadNMkW1sq0Z5w==,type:str]
    dbname: vaultwarden
    host: vaultwarden-pg-rw.vaultwarden
    port: "5432"
    uri: ENC[AES256_GCM,data:tm1t+gXwSTSXeZpfuuFYsGPWBfWLVdtxKc/sMGnZS6BOtttPQzqAbEvHcp7egmNYsPsOiA8em2jSNhcuav2mA81texgDRY6l7um+9EIJb+Glhps3WlCeuwCZewqm/cs=,iv:kgNB1I2pNioQ7f8PF3DK1COpbLlROWS2h1Mt9mAJ4BE=,tag:j/QlVgoPSQ3s4W1w1BFK1Q==,type:str]
sops:
    age:
        - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMmx6cWJPRVFiQkMxRFls
            cmhvZkRGNDFGY1hhb3dRaGVQSzkxOE4zdUNvCmJ6WVBPUnFBUkpiUkUrTmRXNUFU
            SWpuYnVLakp0YzVSeS9VSDRYdWNuZTgKLS0tIDFUSy8yTFJhL0dCV2tTSEh5QTA5
            WWU1ZVd5WGhQWEJaQm9mdzJIRXNVbVkK5SuJv6R6BIPzt1rZg5K961kpJ7qzAr2L
            4iegu0841Fc5rZ+y2vlWSWWZaqoiowT+MfIjMpUVRDxUyQea7kO/Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-15T17:33:41Z"
    mac: ENC[AES256_GCM,data:P39oR+BAzZUa3HNmI6gJPp0iS7v9thQFKv5wHNJ533QgvtYtC5LF7tYbtXwSG006Fl6D7wiC4FTGCcWW5GqackmQ3usNNsPud92cHFcrvBETVX/obyzit8R7tlgkUn7kYk1dK6fz5RpCNafr8iNh0zY2NJSfpRcO1OW66k3s1fk=,iv:wFSBPIsVhmFqqUPiKSeFKYFDKxFxIw6hrWZ+WZZgLqc=,tag:R5xbeOalASnxtaZIKphnGA==,type:str]
    encrypted_regex: password|uri
    version: 3.10.2
