version: '3'
tasks:
  bootstrap-leader:
    desc: Setup a leader node with k3sup
    cmds:
      - k3sup install --context homelab --merge --no-extras --local-path ~/.kube/config {{ .CLI_ARGS }}

  bootstrap-agent:
    desc: Setup an agent node with k3sup
    cmds:
      - k3sup join --ip $AGENT_IP --user $USER --server-ip $LEADER_IP --ssh-key $SSH_KEY

  bootstrap-aws:
    desc: Setup AWS account bootstrap
    cmds:
      - | 
        aws cloudformation deploy --stack-name=bootstrap \
          --template-file aws/aws.yaml \
          --capabilities CAPABILITY_NAMED_IAM \
          --tags "project=homelab created-by=bootstrap"
        aws cloudformation describe-stacks --stack-name bootstrap --query "Stacks[0].Outputs"

  bootstrap-flux:
    desc: Setup Flux for GitOps and create
    cmds:
      - |
        flux bootstrap github \
          --components-extra=image-reflector-controller,image-automation-controller \
          --owner=twaslowski \
          --repository=homelab \
          --branch=main \
          --path=clusters/homelab \
          --personal \
          --token=${GITHUB_TOKEN} \
          --read-write-key \
          --context=homelab

  bootstrap-sops-age:
    desc: Setup SOPS with age encryption
    cmds:
      - |
        age-keygen -o age.key
        grep "public key" age.key | sed 's/# public key: //' > clusters/homelab/.sops.pub.age

        kubectl create secret generic sops-age \
          --namespace=flux-system \
          --from-file=age.key=age.key \
          --context=homelab