version: '3'
tasks:
  bootstrap-leader:
    desc: Setup a leader node with k3sup
    cmds:
      - k3sup install --context homelab --merge --no-extras --local-path ~/.kube/config {{ .CLI_ARGS }}

  bootstrap-agent:
    desc: Setup an agent node with k3sup
    cmds:
      - k3sup join {{ .CLI_ARGS }}

  bootstrap-aws:
    desc: Setup AWS account bootstrap
    cmds:
      - | 
        aws cloudformation deploy --stack-name=bootstrap \
          --template-file bootstrap/aws.yaml \
          --capabilities CAPABILITY_NAMED_IAM \
          --tags "project=homelab created-by=bootstrap"

  bootstrap-flux:
    desc: Setup Flux for GitOps and create
    cmds:
      - |
        flux bootstrap github \
          --owner=<your-account> \
          --repository=homelab \
          --branch=main \
          --path=clusters/minimal \
          --personal \
          --token=${GITHUB_TOKEN} \
          --context=homelab

        age-keygen -o age.key
        grep "public key" age.key | sed 's/# public key: //' > clusters/homelab/.sops.pub.age

        kubectl create secret generic sops-age \
          --namespace=flux-system \
          --from-file=age.key=age.key \
          --context=homelab