apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-operator
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - postgres-operator
  selector:
    matchExpressions:
      - key: app
        operator: Exists
        values:
          - postgres-operator.crunchydata.com/control-plane
  podMetricsEndpoints:
    - port: metrics