apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: kube-state-metrics-config
    files:
      - kube-state-metrics-config.yaml=kube-state-metrics-config.yaml
  - name: kube-prometheus-stack-values
    files:
      - values.yaml=prometheus-values.yaml
secretGenerator:
  - name: kube-prometheus-stack-secrets
    files:
      - values.yaml=prometheus-values.enc.yaml
configurations:
  - kustomizeconfig.yaml