grafana:
  adminPassword: ENC[AES256_GCM,data:3SZHf21rT4e4BxC9y2DH8B+A4ZHLHw==,iv:gKtoHLrXdy/EqnPdkb5TXbI4fwHEsLN0Q9lnqLDkGnU=,tag:mYqhrMU0etfLOpBGJRom9g==,type:str]
sops:
  age:
    - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNHV6ODcvZWNwMlBsajhF
        SloyeWw5c2huTldXcjgyL2VnTUlvckR0N3hjCmFsNXpsWVR3YVg0dXdJeXI5Wmcz
        QlVXMTBERlFpZWQwYmFWSjQ2dXFUSDAKLS0tIHBuWjBxN2VFdWZWbDNCODFodW44
        c1JmaFVrNHJlR1FYVVU4Yzd0YnczZUUKDjzPrLvZBY8j8jnYejz8AZTuyIvj1PSD
        fo25qshKhirqdYmUINlEZMHnApqU17trNvR2LaFVbCWkvxr5uMPqlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-28T12:15:10Z"
  mac: ENC[AES256_GCM,data:V+SB7YGgOsAamIvwb3XMV1pu1EblIyfxVxPcmoPZc1jJnM/pTyLRu/aGM9cfcZ0yBVDJ6k+hFhXT+UtxifTWYUDcOWjOEcaPL61uCZaLNX2ROZONH8RVqCh8EnnpqZxOFpNxAtXRi8vO6Z01KH9xqORoJBQPzfgDrFhmauBXsTk=,iv:XQwTTcZs0rgCS3z7+LP6Jol3z67qHeaPfgFvEDrJ3rQ=,tag:59PArn41v9lfLfBv3PKDmQ==,type:str]
  encrypted_regex: adminPassword
  version: 3.10.2
