apiVersion: v1
kind: Secret
metadata:
  name: thanos-config
type: Opaque
stringData:
  thanos-config.yaml: ENC[AES256_GCM,data:QdejvE6LVXyvh/PSYeT0rdIirY1878pjUQBIWSli+tL/yjKnx7vGklMLeL1pz3drfDwKwGBTK7NIkXJjEwK9LEoERZkIKUUe9GvSfEcI1hvVO6qoed1Ge6uMHCMO88/IKuc8ghDpp7LKbMhCo5Zlsig5xd5NRqOgPcQbyZAGTM895Oap5hvaKLGkCokwvnaPvSmTsZrbszMvQRpPMC+j3UPl4+jPZmXftI9MX3mTLFt5iXETcYuxqxv2L1iQ3acR+FYhAdoTDvtsG57mxjUjz65dDWdHIorMgbeF,iv:H3PE1ncwGWe/N8EA+OFdIgUTavsNLO4uc4ARLjesrGQ=,tag:hLgo+OffhyduYhI/H+t9Kg==,type:str]
