apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale
resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml
secretGenerator:
  - name: tailscale-values
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml