apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  interval: 15m
  chart:
    spec:
      chart: tailscale-operator
      version: "1.88.2"
      sourceRef:
        kind: HelmRepository
        name: tailscale
      interval: 15m
  valuesFrom:
    - kind: Secret
      name: tailscale-values