apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configMapGenerator:
  - name: grammr-dashboards
    files:
      - dashboards/core.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: grammr
        kustomize.toolkit.fluxcd.io/substitute: disabled