apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
configMapGenerator:
  - name: tandoor-values
    files:
      - values.yaml=values.yaml
secretGenerator:
  - name: tandoor-secrets
    files:
      - values.yaml=values.enc.yaml
    type: Opaque
configurations:
  - kustomizeconfig.yaml