apiVersion: v1
kind: PersistentVolume
metadata:
  name: tandoor-media
spec:
  capacity:
    storage: 100Gi # Ignored, required
  accessModes:
    - ReadWriteMany
  storageClassName: "" # Required for static provisioning
  claimRef:
    namespace: tandoor
    name: tandoor-media-s3
  mountOptions:
    - allow-delete
    - region eu-central-1
    - prefix csi/tandoor/media/
  csi:
    driver: s3.csi.aws.com
    volumeHandle: tandoor-tandoor-media  # namespace, pvc name
    volumeAttributes:
      bucketName: 246770851643-eu-central-1-homelab-cluster-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-media-s3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi # Ignored, required
  volumeName: tandoor-media
