apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor
spec:
  interval: 15m
  chart:
    spec:
      chart: tandoor
      version: "0.9.9"
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: flux-system
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: tandoor-values
    - kind: Secret
      name: tandoor-secrets