env:
  TZ: "Europe/Berlin"
  DB_ENGINE: "django.db.backends.postgresql"
  POSTGRES_HOST: "tandoor-pg-rw"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "tandoor"
  POSTGRES_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: pg-secret
        key: password
  POSTGRES_DB: "tandoor"

controller:
  strategy: Recreate

securityContext:
  runAsUser: 0
  fsGroup: 0
  runAsGroup: 0

nodeSelector:
  kubernetes.io/hostname: homelab-leader

ingress:
  main:
    enabled: true
    ingressClassName: "cloudflare-tunnel"
    hosts:
      - host: tandoor.twaslowski.com
        paths:
          - path: /
            pathType: Prefix
            service:
              port: 8080
          - path: /static
            service:
              port: 80
          - path: /media
            service:
              port: 80

persistence:
  media:
    enabled: true
    size: 2Gi
    accessMode: ReadWriteOnce
  config:
    enabled: true
    size: 50Mi
    accessMode: ReadWriteOnce
  django-js-reverse:
    enabled: false
  static:
    enabled: false

postgresql:
  enabled: false