datasources:
  - name: CloudWatch
    type: cloudwatch
    jsonData:
      authType: keys
      defaultRegion: eu-central-1
    secureJsonData:
      accessKey: ENC[AES256_GCM,data:o98U4Fjwb/OA66Gu7HBBU3+2N+w=,iv:zPJnuTmSsBhXfvt9W1tVdnPdLSCX2xU3CnKwYY3kCCk=,tag:EEYmQXl9o544TeKifi2qWQ==,type:str]
      secretKey: ENC[AES256_GCM,data:iQIMNBD0btHIPxpCJgUAccRDSlhtm+F4nQ/r0h5ziQDsTv1UMZV5zA==,iv:Vg8CzBV1W7Rns8uenJ3tHpHP4TsvQjVKkFJiZ6qky7c=,tag:BBk7+nE7lsDPkBKDq1RqaA==,type:str]
sops:
  age:
    - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYWlqTkhQMmVraWV4LzlX
        YzFDakpZRjZWbElwT0wvQitvUE1zTklMMVc0Ci9RQTVIS0YzdVpjcE9FdnQ5UTRl
        bVl4d3pVU05JZEZYTWI3NFJJWlI0SXcKLS0tIERXRFkxQVJnU3FHZXUza3hPQVl0
        NDBRNGMwYWExSWRJb0FHTFpoR054bkkK7ukRgxDEx2kZCBGOUTgeUW4W5/P+K6Vs
        XQEuvxY+SHTWgx0Nu0fvq+ivuCTBSU6GR1KxeEwacXf7+reMhtkgWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-07T13:51:36Z"
  mac: ENC[AES256_GCM,data:AErkjQ6j5qvZZ59WEldmh1n0+x8xvHPPFPq7yydHu6O/IHZvx5PgGsewRg/ah/tnpOcIL2cR/8B6fezwpfj3+uRllqpnEwiw5cqfSqRRrHDEJiOaCxC/EMLdDxHTkQmTfafexh8gT8exF98lFSTuXFFew2IZUN8WooYU6IDo3j0=,iv:5jElk5VIzzAF88OP+EEJ3MqyNJmqM1MJjX5+9VjtT3g=,tag:bIvh/UfPoP4Gwmp8wFFxmg==,type:str]
  encrypted_regex: secureJsonData
  version: 3.10.2
