apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - release.yaml
configMapGenerator:
  - name: postgres-values-cm
    files:
      - values.yaml=postgres-values.yaml
secretGenerator:
  - name: postgres-values-secret
    files:
      - secret.yaml=postgres-values.enc.yaml
    type: Opaque
configurations:
  - kustomizeconfig.yaml