s3:
    accessKeyId: ENC[AES256_GCM,data:4tWikSNAGwU9r/KGU5tTBxHCDL4=,iv:JAlzSrcOwuJMyovGURGKoKZAjxrfoh3qiND4R5/rYcg=,tag:iIPXMh1kOMhAc9rPvCAMSQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:RbuB3p1h7zaW0TZdjuGz6rDxS4WQGvkMbMc0cTtemifAsgpFv5vdgQ==,iv:G1/Hn1wvKaoTHKKiq3OHOeCW/UIm+0Dp3fJIs8BGuqY=,tag:+WwagcoRkFSnSvmQuexIvw==,type:str]
    bucket: ENC[AES256_GCM,data:sRrM7jVvU0KMbGCxssXAzsUz925Uaz6vx54mR4EI0R1aSN/Fig==,iv:po3IZa9WaMBcN74Wyr9CYIXRYVAkTy19JKqL2/DqHPU=,tag:1qA1ekVC+pJvUtgp7+uIeA==,type:str]
    region: ENC[AES256_GCM,data:cvPOAMlIw3egVgA5,iv:pnVIyMNc1BaWNNui7tlTjgPjfkprZ0WIk1dIgav8RH4=,tag:d0TroQuW2YJh2eMxdhbv9w==,type:str]
sops:
    age:
        - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZHVIUnlKczVmSUl1SUJL
            Q0hnc2pNSFlKWDZOVUhNa1VaSC9nWE5naldZCmNDWFpia2xGMjUrSVMxbnJZbzcz
            ZVFHOHpBMGRoQm4xc0UzcGY3UFloUlkKLS0tIDczalppUkh1RnA1ZVpyOHZzMWFv
            b09iTWJmRDVRRWxiZFNhR2U1N2N3QXMKrrZYVzwpW2nHknnFCmszvzKLFEtZG7w6
            O+6FkDj3zRMAKwCMN8jpT2pxiD7xTwX0i951ras/VZ5sXYwtaXFADw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-11T11:42:35Z"
    mac: ENC[AES256_GCM,data:TXBk6v4DhOyBqwHEK+Jykwse4QzAqSZS8fTo8d0QRgjv4UXDqIHqtx8hM2T+YOM5Hj9s9Z7qVkC73ZgW7bpwjHfuXt1v0H5HUgMBqVus+thLghahCZn/Pg7xUKPjs8k2Kr7o4wjstRrYwkfS9FDEYkJhVHuiJ7TsTqCoLqkT76E=,iv:jkURX/5tpn2utaRLvet5zNDa2a1Rv6BRR/q0YoFfbr0=,tag:3vBCLQ/64BmLYUAA77SJTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
