apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: anki-exporter
spec:
  interval: 15m
  chart:
    spec:
      chart: anki-exporter
      version: "0.3.1"
      sourceRef:
        kind: HelmRepository
        name: grammr
        namespace: flux-system
      interval: 15m
