---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: charts/pgo
      sourceRef:
        kind: GitRepository
        name: homelab-charts
        namespace: flux-system
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: postgres-operator-values
      valuesKey: values.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator-values
  namespace: postgres-operator
data:
  values.yaml: |
    singleNamespace: false

