apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: pgo
      version: "27.22.0"
      sourceRef:
        kind: HelmRepository
        name: homelab
      interval: 15m