apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: inflection-ru
  namespace: grammr
spec:
  interval: 15m
  chart:
    spec:
      chart: inflection-ru
      version: "0.2.3"
      sourceRef:
        kind: HelmRepository
        name: grammr
        namespace: flux-system
      interval: 15m
