apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluent-bit
      version: "0.49.1"
      sourceRef:
        kind: HelmRepository
        name: fluent-bit
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: fluent-bit-values