apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: grammr-develop
spec:
  imageRepositoryRef:
    name: grammr-core
    namespace: flux-system
  filterTags:
    pattern: '^develop-(?P<ts>\d{14})-[0-9a-f]{7,40}$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: update-grammr-core-dev
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1m
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(grammr): automated image update
    push:
      branch: main
  update:
    path: ./apps/homelab/grammr/overlays/dev/core/values.yaml
    strategy: Setters
