apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: grammr-core
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: grammr-core
  filterTags:
    pattern: '^sha-[a-f0-9]+$'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: update-grammr-core-dev
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1m
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        Update grammr-core to {{ .Updated.Image }}
    push:
      branch: main
  update:
    path: ./apps/homelab/grammr/overlays/dev/core/values.yaml
    strategy: Setters
