apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/core
  - image-policy.yaml
  - jwt-public-key-cm.yaml
patches:
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: PodMonitor
      name: grammr-monitor
    path: patch.yaml
configMapGenerator:
  - name: core-values-cm
    files:
      - values.yaml=values.yaml
secretGenerator:
  - name: core-values-secret
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml