apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: scheduled-backup
spec:
  cluster:
    name: grammr-pg
  method: plugin
  schedule: "0 0 3 * * *"
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io