apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grammr-pg
spec:
  instances: 1
  bootstrap:

#    initdb:
#      database: grammr
#      owner: grammr
#      secret:
#        name: pg-secret

    recovery:
      source: origin
      database: grammr
      owner: grammr
      secret:
        name: pg-secret

  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: backup-store
          serverName: grammr-pg

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backup-store-dr

  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
