apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor
  namespace: grammr-dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grammr
  namespaceSelector:
    matchNames:
      - grammr-dev
  endpoints:
    - port: web
      interval: 30s
