apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cnpg
      version: "5.8.3"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      interval: 15m
  values:
    singleNamespace: false