apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: prometheus
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-state-metrics
      version: "6.1.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 15m