apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - namespace.yaml
  - prometheus-server.yaml
configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - values.yaml=kube-state-metrics-config.yaml
configurations:
  - kustomizeconfig.yaml