apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus
      version: "27.22.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      namespace: prometheus