apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-production
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infisical-secret
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infisical-secret
      secretsScope:
        projectSlug: ENC[AES256_GCM,data:ok5Ub7GRlpwu/SzG,iv:fG8cLz2QvU2vtEe7jME1OYeD8nD1WkLeVH87et2ZWwg=,tag:WM6pP3Phy4bFCDMusp6mAg==,type:str]
        environmentSlug: ENC[AES256_GCM,data:ccyZpg==,iv:jebrnVs+JCJ7lrwC+IjrfmEjr734hL/HjEkOpi6R508=,tag:sAOsmePJ/tE6yxOtRjdsZA==,type:str]
        secretsPath: /
        recursive: false
        expandSecretReferences: false
sops:
  age:
    - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYlN2S2gyZXkwd2Zzd0dn
        bHJtUDVSbW53OVhSbWpnOUZQOThUSk5TUGk0Ck53Mks4amJNbXhzK1F3VEJJSE1R
        eTRqckJSdUV2clhBTEZKZGl5WTJza00KLS0tIGxYYUJ2MHVRcXVhSVBKb3RMdENw
        T0lnQmt6anJXbE9aOEhHbUlKSU94ZVEKEcKCOlcwNcyNzxt1DaownqN2mASk5VxR
        MyFQy4Sl2/0a2pboz65miGVBncoDUgGwGFGPpRsN64f/h154Bs9d6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-04T09:08:02Z"
  mac: ENC[AES256_GCM,data:ohRh0+LTQisny6tDskB0IgFe+nvn5aHfeS4BEaEqr5LaNvUsEUiVBqbetFqN3aL8iMOWGwa7rQAlbjNe1OBHyA6zOW8LJcJypbPSzpa6lFkMtPnBDakITGJBN+G/3ukQvfrxMXwMENHLSGEQ2jDOX7Wy1VGXs32vYCBJ0X1idv4=,iv:/WthUpGU8744SOe+IbAHmEiXziQ3FYM+kfAyk6C00GE=,tag:FcvcDrJUQRZ3g91HbpYBvQ==,type:str]
  encrypted_regex: .*Slug
  version: 3.10.2
