apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-production
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infisical-secret
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infisical-secret
      secretsScope:
        projectSlug: homelab-drgy
        environmentSlug: prod
        secretsPath: /
        recursive: true
        expandSecretReferences: false
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-develop
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infisical-secret
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infisical-secret
      secretsScope:
        projectSlug: homelab-drgy
        environmentSlug: dev
        secretsPath: /
        recursive: true
        expandSecretReferences: false