apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-monitoring
  labels:
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions: {}
  podMetricsEndpoints:
    - port: http-prom