apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-monitoring
  labels:
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - source-controller
          - kustomize-controller
          - helm-controller
          - notification-controller
          - image-reflector-controller
          - image-automation-controller
  podMetricsEndpoints:
    - port: http-prom