apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - repository.yaml
  - release.yaml
  - secret.yaml
configMapGenerator:
  - name: kube-prometheus-stack-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml