apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: memos-pg
  annotations:
    k8up.io/backup: "false"
spec:
  instances: 2
  bootstrap:
#    initdb:
#      database: memos
#      owner: memos
#      secret:
#        name: pg-secret

    recovery:
      source: origin
      database: memos
      owner: memos
      secret:
        name: pg-secret

  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: backup-store
          serverName: memos-pg

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backup-store-dr

  storage:
    size: 4Gi
  monitoring:
    enablePodMonitor: true
