apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grammr-shared
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: grammr
  path: ./deploy/shared
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
