apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mood-tracker
spec:
  imageRepositoryRef:
    name: mood-tracker
    namespace: flux-system
  policy:
    semver:
      range: "1.x"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: update-mood-tracker
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1m
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(grammr): automated image update
    push:
      branch: main
  update:
    path: ./apps/homelab/mood-tracker/application/values.yaml
    strategy: Setters
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: mood-tracker
  namespace: flux-system
spec:
  image: twaslowski/mood-tracker
  interval: 1m
  accessFrom:
    namespaceSelectors:
      - matchLabels: {}
