---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-tunnel-ingress-controller
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflare
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.strrl.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: cloudflare-tunnel-ingress-controller
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflare-tunnel-ingress-controller
      version: "0.0.18"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
      interval: 15m
  values:
    cloudflare:
      tunnelName: "homelab-tunnel"
      apiToken:
        valueFrom:
          secretKeyRef:
            name: cloudflare-credentials
            key: apiToken
      accountId:
        valueFrom:
          secretKeyRef:
            name: cloudflare-credentials
            key: accountId

