apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: cloudflare-tunnel-ingress-controller
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflare-tunnel-ingress-controller
      version: "0.0.18"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
      interval: 15m
  valuesFrom:
    kind: Secret
    name: cloudflare-credentials

