apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml
secretGenerator:
  - name: cloudflare-credentials
    files:
      - values.yaml=cloudflare-values.enc.yaml
configurations:
  - kustomizeconfig.yaml