apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflare-tunnel-ingress-controller
      version: "0.0.18"
      sourceRef:
        kind: HelmRepository
        name: cloudflared
      interval: 15m
  valuesFrom:
    - kind: Secret
      name: cloudflared-values
  values:
    cloudflare:
      tunnelName: "homelab-default"