apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homer
resources:
  - release.yaml
configMapGenerator:
  - name: homer-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml