apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homer
spec:
  interval: 15m
  chart:
    spec:
      chart: homer
      version: "0.13.0"
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: flux-system
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: homer-values