controller:
  strategy: RollingUpdate

ingress:
  main:
    enabled: true
    ingressClassName: "cloudflare-tunnel"
    hosts:
      - host: homer.twaslowski.com
        paths:
          - path: /
            pathType: ImplementationSpecific

configMaps:
  config:
    enabled: true
    data:
      config.yml: |
        title: "Homelab"
        
        header: false
        footer: false
        
        columns: "3"
        connectivityCheck: true
        
        defaults:
          layout: columns
          colorTheme: auto
        theme: default
        
        colors:
          light:
            highlight-primary: "#3367d6"
            highlight-secondary: "#4285f4"
            highlight-hover: "#5a95f5"
            background: "#f5f5f5"
            card-background: "#ffffff"
            text: "#363636"
            text-header: "#424242"
            text-title: "#303030"
            text-subtitle: "#424242"
            card-shadow: rgba(0, 0, 0, 0.1)
            link: "#3273dc"
            link-hover: "#363636"
            background-image: "/assets/your/light/bg.png" # prefix with your sub subpath if any (ex: /homer/assets/...)
          dark:
            highlight-primary: "#3367d6"
            highlight-secondary: "#4285f4"
            highlight-hover: "#5a95f5"
            background: "#131313"
            card-background: "#2b2b2b"
            text: "#eaeaea"
            text-header: "#ffffff"
            text-title: "#fafafa"
            text-subtitle: "#f5f5f5"
            card-shadow: rgba(0, 0, 0, 0.4)
            link: "#3273dc"
            link-hover: "#ffdd57"
            background-image: "/assets/your/dark/bg.png" # prefix with your sub subpath if any (ex: /homer/assets/...)
        
        links:
          - name: "Github"
            icon: "fab fa-github"
            url: "https://github.com/twaslowski"
            target: "_blank"
          - name: "LinkedIn"
            icon: "fa-brands fa-linkedin"
            url: "https://linkedin.com/in/twaslowski"
        
        services:
          - name: "Health"
            icon: "fa-solid fa-heart-pulse"
            items:
              - name: "Uptime Monitor"
                url: "https://twaslowski.github.io/homelab-uptime"
                icon: "fa-solid fa-up-long"
                subtitle: "Status & Uptime"
                keywords: "uptime monitor status"
              - name: "Grafana"
                icon: "fa-solid fa-chart-line"
                subtitle: "Monitoring & Analytics"
                keywords: "monitoring"
                url: "https://grafana.twaslowski.com"
                target: "_blank"
        
          - name: "Apps"
            icon: "fa-solid fa-rocket"
            items:
              - name: "paperless-ngx"
                subtitle: "Document Management System"
                icon: "fa-solid fa-leaf"
                keywords: "document management ocr pdf"
                url: "https://paperless.twaslowski.com"
                target: "_blank" # optional html tag target attribute
    
              - name: "Vaultwarden"
                subtitle: "Password Manager"
                icon: "fa-solid fa-lock"
                keywords: "password manager"
                url: "https://warden.twaslowski.com"
                target: "_blank"
