apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - podmonitor
configMapGenerator:
  - name: flux-grafana-dashboards
    files:
      - dashboards/flux-cluster.json
      - dashboards/flux-control-plane.json
      - dashboards/global.json
      - dashboards/nodes.json
      - dashboards/pods.json
      - dashboards/namespaces.json
      - dashboards/cloudnative-pg.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: flux-grafana-datasources
    files:
      - datasources/loki.yaml
      - datasources/cloudwatch.yaml
    options:
      labels:
        grafana_datasource: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled