apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudnative-pg-monitor
  labels:
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - cnpg-system
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - cloudnative-pg
  podMetricsEndpoints:
    - port: metrics