---
AWSTemplateFormatVersion: 2010-09-09
Description: Homelab AWS account boostrap

Resources:
  StorageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${AWS::Region}-homelab-cluster-storage"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireLogFolder
            Prefix: fake/
            Status: Enabled
            ExpirationInDays: 14
          - Id: ExpireBackupFolder
            Prefix: backup/
            Status: Enabled
            ExpirationInDays: 30

  PrometheusBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${AWS::Region}-homelab-cluster-prometheus-storage"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireItems
            Status: Enabled
            ExpirationInDays: 14


  HomelabStorageUser:
    Type: AWS::IAM::User
    Properties:
      UserName: homelab-storage-user

  HomelabStorageUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: homelab-storage-user-s3-access
      Users:
        - !Ref HomelabStorageUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !GetAtt StorageBucket.Arn
              - !Sub "${StorageBucket.Arn}/*"
              - !GetAtt PrometheusBucket.Arn
              - !Sub "${PrometheusBucket.Arn}/*"

  HomelabStorageUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref HomelabStorageUser

  HomelabSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: /homelab/bootstrap
      Description: Stable secret store for homelab
      SecretString: |
        {
          "exampleKey1": "exampleValue1",
          "exampleKey2": "exampleValue2"
        }

Outputs:
  HomelabStorageUserAccessKeyId:
    Description: Access Key ID for homelab-storage-user
    Value: !Ref HomelabStorageUserAccessKey
  HomelabStorageUserSecretAccessKey:
    Description: Secret Access Key for homelab-storage-user
    Value: !GetAtt HomelabStorageUserAccessKey.SecretAccessKey
