apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: grammr-monitor
  labels:
    app.kubernetes.io/part-of: grammr
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - grammr
  selector:
    matchExpressions:
      - key: "app.kubernetes.io/name"
        operator: In
        values:
          - grammr
  podMetricsEndpoints:
    - port: http