apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grammr-core
  namespace: grammr
spec:
  interval: 15m
  chart:
    spec:
      chart: grammr
      version: "3.6.4"
      sourceRef:
        kind: HelmRepository
        name: grammr
        namespace: flux-system
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: core-values-cm
    - kind: Secret
      name: core-values-secret
