apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grammr-dev-certificate
  namespace: grammr-dev
spec:
  secretName: grammr-dev-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  commonName: server.dev.grammr.app
  dnsNames:
    - server.dev.grammr.app
