apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:vRO+51p2,iv:I3BrujCXjXDpyjCBrUyfLdteBgQdiiWBY9Wqb8TKnoo=,tag:UF0tRJh4+iljwvwWLzW21Q==,type:str]
  password: ENC[AES256_GCM,data:sLzgW85qHvQyYugBwtBpOsyyx/bMhVYcY2+Gf78lqr4y+DjlktCgYxWgZ1htmnpLDZj1Nljzp1pd,iv:aRdcbHu8VrzyB6fuir8yQl2pZ0pkfDMUxkagg5aLo28=,tag:L3Lspa9q+Z0Nq4DD8uh3Cw==,type:str]
  dbname: ENC[AES256_GCM,data:VUDlnYEn,iv:KgrFT24Ul1BlTpbiUUVwgL8usbUjgVWqd9bVtpvXl3A=,tag:sXmuUysW4XKlbujY6Oz68A==,type:str]
  host: ENC[AES256_GCM,data:hNX5guLfymZCA3Hd,iv:0ATqDgqQxScs8a90OG+ZzNI0dqiFUv63BRq7U2ybgVk=,tag:4GJZaIO6+BdGnLdBj7pOgg==,type:str]
  port: ENC[AES256_GCM,data:RsPz4Q==,iv:CiCXCWZCgtfX8RIF3T8WW+vWnZp7hsCxWGYLbCJPNxc=,tag:UNbrjcEDJKLsuTXlJqBREQ==,type:str]
  jdbc-uri: ENC[AES256_GCM,data:C1ddd+8zUq3uT52NPaSJfkSK9lTyrsVRe3yAHBR4C/daVKoqC33LQ5zkPcDMSZA8z+UCcfur/xeQiqJckAWfDgt6zDHezM1FmCeLhT4JzUTz7/VDFRh8cj3cLnNfGmt1HOGJoT2k+iUaKrGyl2OAUMgddH7y3HT/wkhzT9FqYN4+i2k0oQqfQOO3QlN6OQ==,iv:0S/tcScWy7aDUdvXKgchBShGW515LRELhuXtySXj6BI=,tag:rG3/yYm3aEQIsJIuESsJJg==,type:str]
  uri: ENC[AES256_GCM,data:eGtnW6sWuzJa321qb69lf/sMhVyZvBVwHS2JhJqj65ZkFUmWRoFLTpowyUEgL9GIgXS2m+YOGIXsH32iphxKnSOFcjde44CBBsgI1GoWDO0R83LfWP4DNpsE7K8qx40/GnAzg8V07R+84Lp8sshMx6g=,iv:vj8VUHCttrXVqEQnS2WbrvxUauu8zrrcSdWAzNsDqk8=,tag:w+OBpEY5tN7Tpbfh0DaYVw==,type:str]
sops:
  age:
    - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvM0Exd2tuZjA4TkYvOG96
        NkpFWVhld1hXMWViZ1ZzUUpubHVVWHJOVEdJCllMMDVucTJkcVRjSGtBQUNRV1hr
        aGovL3hRNG1iM3l2dzhBcDFjTWsyaWMKLS0tIHNkZzh5RktSaDM5VHh2dGF2SkVz
        Z1A3YVUyY0pGL0N4VUZYdUc1eC9VN0EKXJ7jzcuPDKbt2hDk30A/AtpO5mWuMfh5
        mFUkt8YTPTA+c/PKC748q66NL4wA+YfU31y5kM+cLwo0vaCtO7gIqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-29T14:56:13Z"
  mac: ENC[AES256_GCM,data:bMwjG6sinFnxVlXsBFJqFPq+jf0lCMjyymW1MzqnI97ttHQ5Gl2ZMChgm65loqEQE9EZVB9rLgjdPRWtgKIcJOWxG/NB7tOmwSLB6zWf8tyeyst9vpJPJfrX9wnstdcO131QdvTzo9+h0jvbuV578slRc4KmoiqmrymVH3I2zEM=,iv:KuJizmXg9ZDlODDnN4MSqncvo+1/2AA7+h9gcXn6xdU=,tag:+DfxvxL5ATGnaAZlNnUXTQ==,type:str]
  encrypted_regex: stringData
  version: 3.10.2
