apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: grammr
  password: ENC[AES256_GCM,data:k69E/HYLAlkPH4RDGyz+eVO4JJNTCCyA+VpKAjjtrJBkbC3+Xh2LuBzyUelHLWaH1EsMaQr/GxPk,iv:Xr674ePS0zI1GnE1gtJJGDxIXl1N7yZW1JIKuGLWWw4=,tag:dHLuLryeeTgkichnyt4Bxw==,type:str]
  dbname: grammr
  host: grammr-pg-rw.grammr-dev
  port: "5432"
  uri: ENC[AES256_GCM,data:Uirosgwe/bocSfwsirN1swEkv/tiR2+69gxW3+p6BTqF9+dSCMyP4bNgsAhL69lqf153KAWYjxDb4U/am/EQvb9u/MzGswMRNfchQr+LqoKChSTE5LGj2ufurX5vYEspLd3tQqIkzPeD+QmcJyOQwQg=,iv:+Hp5NdUiSKa/Xh3KqP34wZMGC2qhu+QpeZT48IMOi2s=,tag:MrKCRGcBZcHkf2e7IFBDwg==,type:str]
  jdbc-uri: ENC[AES256_GCM,data:ocSc/ILk6L65sqkNht9OAvHD5R17bL/CFwcm3ScQlPDDcgXS+jSn64nx2VSG7RJXizJXJRYmWlvbig3PzXl65vBtv/NqaLY6Xitcvhx5V9Nl8EzVgP+4puryCxZm6bRGrbof3M2l6ucIRrLxP3+ZajtVeZVhYUAruBhn7+4306glzRr+,iv:0IU6sCvq1AjkX2fPd8SawVEcAE5SIzg1wNA1gOzV/dI=,tag:9HAWC58SNSw/yoFEPLOWKA==,type:str]
sops:
  age:
    - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTzlicWduSENMWU40SFNK
        UjN2Vi9NdjJ6eUhBb3E0bVdxMjkyVnZNL2swCk5XRTVyLzVITTJHRG5LRUFvS2hR
        MnpTSytGWGg3enZJMXByMDk5c1dtajAKLS0tIHBBdVdWQ0hVR3RNcTlJZUtueDFi
        Skw4RXN6UXRibTJmamdNYUg0Zm5ubVkKvIvJSIM2L6T10GF+ZqT5i//THVjn6Stk
        y87mNtN9SQz52X8HTjylIls4zaZPg9LXB9PA8LArVtSsvIrAiGE9sg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-20T15:21:23Z"
  mac: ENC[AES256_GCM,data:JAI8BoZ51GLgrSNExOyrzCiIl2fZARhZXdtxZOhf+gYGFrDJUBAk8x+GwNwlJfMJIBH2AVBm+S8f6SzZVls/PChjJTihXz8XCU4WA4PKZsMbBCp5z7Dg2gN4nAkqeDXWbvWHqn0EcLR3AdEQml0EVZN7ydrVzA1G2aNK2IxkF4A=,iv:x+gqnHfpcKGS4G3as4doR5gA3HX543GtkecZhMXEKy8=,tag:YlWEMCQPiY3PLpm/wgEnrQ==,type:str]
  encrypted_regex: password|.*uri
  version: 3.10.2
