{{ if and .Values.databaseInitSQL.enabled .Values.databaseInitSQL.content }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-cluster.fullname" . }}-database-init-sql
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "postgres-cluster.labels" . | nindent 4 }}
data:
  initSQL: |
{{ .Values.databaseInitSQL.content | nindent 4 }}
{{ end }}

