apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  labels:
    {{ include "postgres-cluster.labels" . | nindent 8 }}
  name: {{ include "postgres-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{ if .Values.backups.enabled }}
  backups:
    pgbackrest:
      configuration:
      - secret:
          name: {{ include "postgres-cluster.fullname" . }}-pgbackrest-secret
      global:
        repo1-path: {{ .Values.backups.pgbackrest.global.repo1Path | default (printf "/pgbackrest/%s/%s/repo1" .Release.Namespace (include "postgres-cluster.fullname" .)) }}
        repo1-retention-full: {{ .Values.backups.retentionDays }}
        repo1-retention-full-type: time
      repos:
      - name: repo1
        schedules:
          full: {{ .Values.backups.schedules.full }}
          differential: {{ .Values.backups.schedules.differential }}
        s3:
          bucket: {{ .Values.s3.bucket }}
          endpoint: {{ .Values.s3.endpoint | default (printf "s3.%s.amazonaws.com" .Values.s3.region ) }}
          region: {{ .Values.s3.region }}
      manual:
        repoName: repo1
        options:
          - "--type=full"
  {{ end }}
  {{ if .Values.restore.performRestore }}
  datasource:
    postgresCluster:
      clusterName: {{ .Values.restore.clusterName | default (include "postgres-cluster.fullname" .) }}
      clusterNamespace: {{ .Values.restore.clusterNamespace | default .Release.Namespace }}
      repoName: {{ .Values.restore.repoName }}
  {{ end }}
  {{ if .Values.databaseInitSQL.enabled }}
  databaseInitSQL:
    key: initSQL
    name: {{ include "postgres-cluster.fullname" . }}-database-init-sql
  {{ end }}
  instances:
  - dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    name: instance1
    replicas: {{ .Values.database.replicas }}
  port: {{ .Values.database.port }}
  postgresVersion: {{ .Values.database.postgresVersion }}
  users:
  {{- with .Values.users }}
  {{ toYaml . | nindent 8 }}
  {{- end }}
