apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-cluster.fullname" . }}-pgbackrest-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "postgres-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  s3.conf: |
    [global]
      repo1-s3-key={{ .Values.s3.accessKeyId }}
      repo1-s3-key-secret={{ .Values.s3.secretAccessKey }}
