loki:
  server:
    http_listen_port: 3100
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    # 14 days
    retention_period: 336h
  ruler:
    enable_api: true
  storage_config:
    tsdb_shipper:
      active_index_directory: /tmp/loki/index
      cache_location: /tmp/loki/index_cache
  storage:
    type: s3
    s3:
      s3: s3://246770851643-eu-central-1-homelab-cluster-storage
      accessKeyId: ENC[AES256_GCM,data:IiJjOBbn6uweda/5lAMJICTuqrU=,iv:NArg/L4MS7OXGq9i4BYblAvqi2CjB5Ag2fBLKHDayto=,tag:sNLxPqQ7NHX5hrWDBbLvQA==,type:str]
      secretAccessKey: ENC[AES256_GCM,data:mwPgqqqscDrqVr7jD107nQdSkDA7Ap2ePq/c3IQ1+Ujj8bnp6p+j6Q==,iv:8zv4LDsck921bZPAtxmPdmZnbOJV0HVJIxv0rWUKy3Q=,tag:qH/aB2aFdreAqJcHYV5jng==,type:str]
      region: eu-central-1
      endpoint: s3.eu-central-1.amazonaws.com
      insecure: false
      s3ForcePathStyle: true
      s3UrlStyle: path
    bucketNames:
      chunks: 246770851643-eu-central-1-homelab-cluster-storage
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: "0.5"
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 3Gi
  nodeSelector:
    kubernetes.io/hostname: homelab-leader
minio:
  enabled: false
# the chunksCache does not work well on Raspberry Pi
# in any case, the performance benefits it offers likely are not relevant at this scale
chunksCache:
  enabled: false
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
sops:
  age:
    - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ3RXVmFKM2dXZWRwbjAr
        SlRGZU5qUHNhMzZ2YUZiemkzemlHcHovTnpVClRaS0tId0lLcWp3aXZHcEZXU0ZO
        N2pXbnFNMHNKa0gyajI4YlB2Y2RTakUKLS0tIDUweDZaN2hJbmI1ZlFvL1BsS2ti
        Si9hS3NJbVcrUFBkM0xzbGxSSUthWjAKZHOSLG1N9x222JVzQUvtpeiKtG1ggsLs
        Ua9GuEwHw8JSyLoJUG0ZGgD5tqtTjHkcPlaoEcguv/MxsMAeol8/fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-18T14:06:21Z"
  mac: ENC[AES256_GCM,data:dpZZmvamV4lP+X6nucOKobNZAl4wJp+2aWYtHFL49JVM704OKwj3WBwGImvpzPemSnr9ymLinmgDQmFB6gEuw4k70JxZEbK6AWvYpwAw04YCFk5k31DpntaaHoHV3E8+mm9iGOU5m/Pk7Zk+P9tDKClHu7K54YSDihq8T4v81zo=,iv:kFyFUhvmCvQIF7vqgCOlBhxlH1UvYHSLqloHJ2PbzsA=,tag:iB8VCYI+l3mIw0muxziskA==,type:str]
  encrypted_regex: secretAccessKey|accessKeyId
  version: 3.10.2
