loki:
  server:
    http_listen_port: 3100
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    # 14 days
    retention_period: 336h
  ruler:
    enable_api: true
  storage_config:
    aws:
      region: eu-central-1
      bucketnames: 246770851643-eu-central-1-homelab-cluster-storage
      s3forcepathstyle: false
  storage:
    type: s3
    s3:
      endpoint: s3.amazonaws.com
      region: eu-central-1
      secretAccessKey: ENC[AES256_GCM,data:ZbRyy0h4TGhQRCCuRCzQF6Rzv7g=,iv:v8of2lx2uxLpyyTzyKFK9Hkmi7ISWZVKLYFDTkuYeKs=,tag:TjEU6yeFFvZe6mtHzzR6bQ==,type:str]
      accessKeyId: ENC[AES256_GCM,data:1t6nYY3ygwkG0E3QPAURRDOXb58bu3kEHSV+KFiewbJkT2+5anZF0w==,iv:otkdwncWvVZWSWCqfcu4V4ZamFa/UzqKH34D+/HwO5k=,tag:iM2NMvdr/6UBx3Ab2P7OOQ==,type:str]
    bucketNames:
      chunks: 246770851643-eu-central-1-homelab-cluster-storage
      ruler: 246770851643-eu-central-1-homelab-cluster-storage
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: "1"
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 3Gi
  nodeSelector:
    kubernetes.io/hostname: homelab-leader
minio:
  enabled: false
# the chunksCache does not work well on Raspberry Pi
# in any case, the performance benefits it offers likely are not relevant at this scale
chunksCache:
  enabled: false
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
sops:
  age:
    - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TzRtWUIweWRoZHBVQ0F1
        d1lSZzFxa3BoMkhBVjlYM2ZVWW1VNFkxM0ZZCkptTDBmZVJETWhTckg3YXZrYXE3
        TnljZk9PdGJ5V2VYM1pMbW84VElTVzAKLS0tIDY3NGFBNkZMcmh1QnhSbDJnVkY4
        RGFyTjBJejh0K0pPMk56cGNGTkhOSnMKXCRXKvJv3SUnKNzkHHGTITDu/fQMU+Ev
        SAGKXXSk8D39Wna6ppg0JyLi/6hiQo48xtCMYLiD5JNFYuVvzwooVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-17T09:22:35Z"
  mac: ENC[AES256_GCM,data:mGxD6jpGKFpbUu2RQ+UMhRImkDYCfga4kV4EXoU/jmcyx0TZEAkdBDhfU8qbyGGn2oIR0LZqb01fChItlEFWQblkTk4VZlKJ5woYak6lBmplmqVIfmw56d1ainq5VdPQ1NiCF9qnbk5y+FP5YZ59Jl+exYWScnyQH5H0FRQt6IE=,iv:71mH4Nb5lXB3UGMzAfIrawzQ+VjA4Lk1W3bG6f9Ql2I=,tag:viqK14nVAPxyjVsVKtimKg==,type:str]
  encrypted_regex: secretAccessKey|accessKeyId
  version: 3.10.2
