# Values reference: https://grafana.com/docs/loki/latest/setup/install/helm/reference/
global:
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    secretRef:
      name: loki-s3-credentials

loki:
  server:
    http_listen_port: 3100
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    # 14 days
    retention_period: 336h
  ruler:
    enable_api: true
  # https://grafana.com/docs/loki/latest/setup/migrate/migrate-storage-clients/#amazon-s3-storage-migration
  # As far as I can tell, both storage_config and storage are required for S3 to properly work.
  storage_config:
    use_thanos_objstore: true
    object_store:
      s3:
        bucket_name: 246770851643-eu-central-1-homelab-cluster-storage
        endpoint: s3.amazonaws.com
        region: eu-central-1
        access_key_id: ${AWS_ACCESS_KEY_ID}
        secret_access_key: ${AWS_SECRET_ACCESS_KEY}
        dualstack_enabled: false
        storage_class: STANDARD
        max_retries: 5
  storage:
    use_thanos_objstore: true
    type: s3
    object_store:
      s3:
        bucket_name: 246770851643-eu-central-1-homelab-cluster-storage
        endpoint: s3.amazonaws.com
        region: eu-central-1
        access_key_id: ${AWS_ACCESS_KEY_ID}
        secret_access_key: ${AWS_SECRET_ACCESS_KEY}
        dualstack_enabled: false
        storage_class: STANDARD
        max_retries: 5
    bucketNames:
      chunks: 246770851643-eu-central-1-homelab-cluster-storage
      admin: 246770851643-eu-central-1-homelab-cluster-storage
      ruler: 246770851643-eu-central-1-homelab-cluster-storage
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  affinity: { }
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      cpu: "1"
      memory: 3Gi
  nodeSelector:
    kubernetes.io/hostname: homelab-leader
  extraEnvFrom:
    - secretRef:
        name: loki-s3-credentials
  extraArgs:
    - -config.expand-env=true

minio:
  enabled: false
# the chunksCache does not work well on Raspberry Pi
# in any case, the performance benefits it offers likely are not relevant at this scale
chunksCache:
  enabled: false
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

