loki:
  server:
    http_listen_port: 3100

  auth_enabled: false

  commonConfig:
    replication_factor: 1

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  pattern_ingester:
    enabled: true

  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    # 14 days
    retention_period: 336h
  ruler:
    enable_api: true

#  storage_config:
#    aws:
#      region: eu-central-1
#      bucketnames: 246770851643-eu-central-1-homelab-cluster-storage
#    tsdb_shipper:
#      active_index_directory: /loki/index
#      cache_location: /loki/index_cache
#      cache_ttl: 24h

#  storage:
#    type: s3
#    s3:
#      region: eu-central-1
#      endpoint: s3.eu-central-1.amazonaws.com
#      insecure: false
#      s3ForcePathStyle: true
#      s3UrlStyle: path
#    bucketNames:
#      chunks: 246770851643-eu-central-1-homelab-cluster-storage

deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "3Gi"
  nodeSelector:
    kubernetes.io/hostname: homelab-leader

minio:
  enabled: true

# the chunksCache does not work well on Raspberry Pi
# in any case, the performance benefits it offers likely are not relevant at this scale
chunksCache:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
