fullnameOverride: core

environmentVariables:
  - name: DATASOURCE_URL
    valueFrom:
      secretKeyRef:
        name: pg-secret
        key: jdbc-uri
  - name: ALLOWED_ORIGIN
    value: https://dev.grammr.app
  - name: ANKI_EXPORTER_URL
    value: http://anki-exporter:8000
  - name: SPRING_PROFILES_ACTIVE
    value: runtime
  - name: JWT_PUBLIC_KEY
    valueFrom:
      configMapKeyRef:
        name: clerk-jwt-public-key
        key: jwt-key.pub
  - name: CLERK_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: clerk-secret
        key: secret-key

ingress:
  enabled: true
  className: cloudflare-tunnel
  host: server-dev.grammr.app
  paths:
    - /api/
    - /actuator/health

languages:
  - code: ru
    morphology:
      enabled: true
      uri: http://morphology-ru:8000/morphological-analysis
    inflection:
      enabled: true
      uri: http://inflection-ru:8000/inflect
