apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - secret.yaml
configMapGenerator:
  - name: kube-prometheus-stack-values
    files:
      - values.yaml=values.yaml
  - name: kube-state-metrics-config
    files:
      - kube-state-metrics-config.yaml=kube-state-metrics-config.yaml
configurations:
  - kustomizeconfig.yaml