crds:
  enabled: true

alertmanager:
  enabled: false

prometheus:
  ingress:
    enabled: true
    ingressClassName: cloudflare-tunnel
    hosts:
      - prometheus.twaslowski.com
    paths:
      - /

  prometheusSpec:
    routePrefix: /
    retention: 4d
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
    podMonitorNamespaceSelector: { }
    podMonitorSelector:
      matchLabels:
        app.kubernetes.io/component: monitoring
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 10Gi

grafana:
  enabled: false
