apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths:
          - /metadata/annotations/prometheus-operator-validated
        target:
          kind: PrometheusRule
  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      valuesKey: kube-state-metrics-config.yaml
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    alertmanager:
      enabled: false
    prometheus:
      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorNamespaceSelector: { }
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
    grafana:
      enabled: true
      defaultDashboardsEnabled: false
      adminPassword: ENC[AES256_GCM,data:lWYifPiKBzTRqrw474IqIC2RWuyqyg==,iv:4bF1UYNnOjHjiqNvvO0ApJ7A2ZoVefAvmVpfnfUq2Rk=,tag:K1HuiWIGgXWVONX9CtiG7g==,type:str]
      nodeSelector:
        kubernetes.io/hostname: homelab-leader
      ingress:
        enabled: true
        ingressClassName: cloudflare-tunnel
        hosts:
          - grafana.twaslowski.com
      datasources:
        datasources.yaml:
          - name: "Prometheus"
            type: prometheus
            uid: prometheus
            url: http://kube-prometheus-stack-prometheus.monitoring:9090/
            access: proxy
            isDefault: true
            jsonData:
              httpMethod: POST
              timeInterval: 30s
          - name: "Alertmanager"
            type: alertmanager
            uid: alertmanager
            url: http://kube-prometheus-stack-alertmanager.monitoring:9093/
            access: proxy
            jsonData:
              handleGrafanaManagedAlerts: false
              implementation: prometheus
          - name: "Loki"
            type: loki
            uid: loki
            url: http://loki.monitoring:3100/
            access: proxy
            jsonData:
              maxLines: 1000
              minLines: 10
              timeInterval: 30s
sops:
  age:
    - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVazY5azB3WkZUL0s5aWU4
        R3pIWGFSY1B1SjZoZXM5dmpYZjh6VzJuanlnCnZtbjREdE5kUVF3Y215c0FvRkhp
        dlBwQ204OGEvNGVVbnB6ZDF0MUpGZG8KLS0tIGtSQXFOdmFFNlUwOTZrK1JpNGdM
        UTlLY1drUkEyOEpOU3h3bDRtQ2ZtVFUKDOv78HhP/3ePz8AKzvC9lQD5cjiiPoO7
        H5rFOOyxI42gs1uHJQoRAdlwZ9qMRzMXcaMPSTme+a4MU8J7S5PQxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-11T14:10:02Z"
  mac: ENC[AES256_GCM,data:pMTMjrPzDBAq8Cko7bNQRf8WHf666Z6bvgedC9Sep4u93LDfeOWQ6ulUGelOk09q3GBWfaRZh4x5U3RKOSXPI6zGtlp3REWOJb4zHhkcZPlYG/Md1O2MQZ5AcfnYKxzLi+YxZKTrW5VOGuGUH+5F0Hm4rG23o8RuAWmaY5RrDxc=,iv:/tNhdNt36agydd2lxVXE5IQ/S7NNkDFgacK604oq6zs=,tag:fNM1lMDnIFNlmZ6vHZDpBw==,type:str]
  encrypted_regex: adminPassword
  version: 3.10.2
