database:
  port: 5432
  postgresVersion: 17
  replicas: 1

nameOverride: ""
fullnameOverride: ""

users: [ ]
#  - name: my-user
#    databases:
#      - my-database
#    options: []
#    password:
#      type: AlphaNumeric | ASCII

backups:
  enabled: true
  pgbackrest:
    global:
      repo1Path: ""

s3:
  bucket: ""
  endpoint: ""
  region: "eu-central-1"
  accessKeyId: ""
  secretAccessKey: ""

databaseInitSQL:
  enabled: false
  content: ""
  #  - |
  #    CREATE DATABASE my-database;
