database:
  port: 5432
  postgresVersion: 17
  replicas: 1

nameOverride: ""
fullnameOverride: ""

users: [ ]
#  - name: my-user
#    databases:
#      - my-database
#    options: []
#    password:
#      type: AlphaNumeric | ASCII

backups:
  enabled: true
  retentionDays: "14"
  schedules:
    full: "0 1 * * 0"
    differential: "0 1 * * 1-6"
  pgbackrest:
    global:
      repo1Path: ""

restore:
  performRestore: false
  clusterName: ""
  clusterNamespace: ""
  repoName: "repo1"

s3:
  bucket: ""
  endpoint: ""
  region: "eu-central-1"
  accessKeyId: ""
  secretAccessKey: ""

databaseInitSQL:
  enabled: false
  content: ""
  #  - |
  #    CREATE DATABASE my-database;
