# values.yaml for fluent-bit Helm chart
namespace: monitoring

fullnameOverride: "fluent-bit"

flush: 1
logLevel: debug

config:
  inputs: |
    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Exclude_Path /var/log/containers/*_logging_*.log
        Parser       cri
        Tag          kube.*

  filters: |
    [FILTER]
        Name         kubernetes
        Match        kube.*
        Merge_Log    On
        Keep_Log     Off
        Merge_Log_Key log
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Kube_Tag_Prefix  kube.var.log.containers.
        Annotations      Off
        Labels           On

    [FILTER]
        name                  multiline
        match                 *
        multiline.key_content log
        multiline.parser      multiline-java


  outputs: |
    [OUTPUT]
        name  loki
        match kube.*
        host  loki.logging.svc.cluster.local
        labels job=fluent-bit, namespace=$kubernetes['namespace_name'], pod_name=$kubernetes['pod_name'], container_name=$kubernetes['container_name'], app=$kubernetes['labels']['app'], service=$kubernetes['labels']['service']

  customParsers: |
    [PARSER]
        Name        java
        Format      regex
        Regex       ^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2},\d{1,3}) (?<level>[^\s]+) (?<message>.*)
        Time_Key    time
        Time_Format %Y-%m-%d %H:%M:%S,%L
        Time_Keep   On

    [MULTILINE_PARSER]
        name                      multiline-java
        type                      regex
        flush_timeout             1000
        key_content               log
        rule      "start_state"   "/\d{4}-\d{1,2}-\d{1,2}T\d{2}:\d{2}:\d{2}.\d{3}Z.*/"  "cont"
        rule      "cont"          "/^(?!\d{4}-\d{1,2}-\d{1,2}T).+/"  "cont"
