apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: vaultwarden-db
  namespace: vaultwarden-dr
spec:
  dataSource:
    postgresCluster:
      name: vaultwarden-db
      namespace: vaultwarden
      repoName: repo1
#    pgbackrest:
#      stanza: db
#      configuration:
#        - secret:
#            name: vaultwarden-db-pgbackrest-secret
#      global:
#        repo1-path: /pgbackrest/vaultwarden/vaultwarden-db/repo1
#      repo:
#        name: repo1
#        s3:
#          bucket: 246770851643-homelab-backrest-backups
#          endpoint: s3.eu-central-1.amazonaws.com
#          region: eu-central-1
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      name: instance1
      replicas: 1
  port: 5432
  postgresVersion: 17
  users:
    - databases:
        - vaultwarden
      name: vaultwarden
      options: SUPERUSER
      password:
        type: AlphaNumeric
