apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-mountpoint-s3-csi-driver
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: aws-mountpoint-s3-csi-driver
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: aws-mountpoint-s3-csi-driver
      interval: 15m
  values:
    controller:
      nodeSelector:
        kubernetes.io/role: control-plane