---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-secret
  namespace: grammr-dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-develop
  target:
    name: pg-secret
    template:
      data:
        user: '{{ .user }}'
        password: '{{ .password }}'
        jdbc-uri: 'jdbc:postgresql://grammr-pg-rw:5432/grammr?user={{ .user }}&password={{ .password }}&currentSchema=grammr'
        uri: 'postgresql://{{ .user }}:{{ .password }}@grammr-pg-rw:5432/grammr'
  data:
    - secretKey: password
      remoteRef:
        key: /grammr/pg/password
    - secretKey: user
      remoteRef:
        key: /grammr/pg/user
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: barman-secret
  namespace: grammr-dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-production
  target:
    name: barman-aws-creds

  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: /aws/access_key_id
    - secretKey: aws_secret_access_key
      remoteRef:
        key: /aws/secret_access_key