apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - release.yaml
  - repository.yaml
configMapGenerator:
  - name: vaultwarden-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml