---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluent
  namespace: flux-system
spec:
  interval: 24h
  url: https://fluent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluent-bit
      version: "0.49.1"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: fluent-bit-values
      valuesKey: values.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-values
  namespace: logging
data:
  values.yaml: |
    namespace: fluent-bit
    
    fullnameOverride: "fluent-bit"
    
    flush: 1
    logLevel: debug
    
    config:
      inputs: |
        [INPUT]
            Name         tail
            Path         /var/log/containers/*.log
            Exclude_Path /var/log/containers/*_logging_*.log
            Parser       cri
            Tag          kube.*
    
      filters: |
        [FILTER]
            Name         kubernetes
            Match        kube.*
            Merge_Log    On
            Keep_Log     Off
            Merge_Log_Key log
            K8S-Logging.Parser  On
            K8S-Logging.Exclude On
            Kube_Tag_Prefix  kube.var.log.containers.
            Annotations      Off
            Labels           On
    
        [FILTER]
            name                  multiline
            match                 *
            multiline.key_content log
            multiline.parser      multiline-java
    
      outputs: |
        [OUTPUT]
            name  loki
            match kube.*
            host  loki.logging.svc.cluster.local
            labels job=fluent-bit, namespace=$kubernetes['namespace_name'], pod_name=$kubernetes['pod_name'], container_name=$kubernetes['container_name'], app=$kubernetes['labels']['app'], service=$kubernetes['labels']['service']
    
      customParsers: |
        [PARSER]
            Name        java
            Format      regex
            Regex       ^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2},\d{1,3}) (?<level>[^\s]+) (?<message>.*)
            Time_Key    time
            Time_Format %Y-%m-%d %H:%M:%S,%L

