apiVersion: v1
kind: Secret
metadata:
    name: pg-secret
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: vaultwarden
    password: ENC[AES256_GCM,data:ebJLFYydumfRyQYhl+cPZIbELsT8sO6Nt2gGjJ8qRcLOfMNcPg==,iv:DHb3qmPjh+psaT84AAwWBvPsYbhlD/oozgtv0Gizn3Y=,tag:n3EGqFNMkcN4m/5h0jwFhg==,type:str]
    dbname: vaultwarden
    host: vaultwarden-pg-rw.vaultwarden-dr
    port: "5432"
    uri: ENC[AES256_GCM,data:2fe7sc+k9QIbcBGbhD7Nwg7tXL0aYWLAUkz01l5eWPDAJ1TrMgCbsfPy2UiweSAYZEaZZQExRjqm8FPF3ewKIE51jIf5QT4YW53QPxyB9hCLFNVLBeIgSDVGg0rGxDAiQ5o0D/JEXfuhPv+R0sj/vA==,iv:SbQTFRQftDWSRgisnn/zJs9z3FqnPKatIqJhIDLFdqc=,tag:y9X1l1eCZVz7zOxyTlj3Mw==,type:str]
sops:
    age:
        - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK25lTFowaXZBUlBaak9D
            WUF0TFM3dVYvdWxlWnZJeDY0aXFaalhoWUhVCkNXZ3IrVUx0NFZoTlkwcWlhRXNX
            d2ZMWFp1U1o3clRxRlhBOG5IS2R2SzQKLS0tIHVyYUo3T1JvMGNzOWlWRlk4ck9w
            blFsTVN6N200YXNpaHppUnlTT09jaTQKLYNDcDf2LLCgEliSvsa36hNF0FtKkkOM
            5OBPYv3hS5+OdIJMYWSIaGlzgwHK2TWlXo+/msrcGM/c1UXteO15EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-20T13:55:07Z"
    mac: ENC[AES256_GCM,data:BrKrw0Cw5BwhE5bkV5wsiyVZcddN1v5KKB6IO+0ljqV11QfNPctrIdN58UqpfLFHCn05D+QCD248nbcge+pMIqnAIyne67jJUKN2QhYN4ga9BrsBUg8AEBXlaUK5+c95VTWOeUU7YV9aOFqLURJMixQnwN93SJvIbOmGPhD38DM=,iv:Z61NhcejUg1hdbrvVcYS0E7YuQo1ixC2HFh9qGUfme0=,tag:Zf1SSsGtio6i/bukh13PyA==,type:str]
    encrypted_regex: password|uri
    version: 3.10.2
