apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: vaultwarden
  password: ENC[AES256_GCM,data:99ngLiD6ksRzace1uJFRkM582vwL4XY=,iv:oAZqZlgoxcNLctWp50fu/I1wY+UDaFmcv2r2156krqg=,tag:3RZzknRAL6mq6482988/8A==,type:str]
  dbname: vaultwarden
  host: vaultwarden-pg-rw.vaultwarden-dr
  port: "5432"
  uri: ENC[AES256_GCM,data:oe/Ruura4AmKJZodd3DBSgzM3ttsJA1GJ5Y7C3r22R+VX3kLuqfyRtYWaz5qPeCaefq1MO4SC5Aqed2KvbaNvs+L/BPejARgn+c869TqwuA8WQ5q/03pNKFzvZDIgfhIMZQ=,iv:NKf8f25ooD0LWBidFdSuuHMsY0NlCMWHFarY+k49X3U=,tag:iqeaBe4BNWTByyo3RkB6QQ==,type:str]
sops:
  age:
    - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ1haNjhxQzNZd3F3VUVv
        c2lVZ1RITXFHUlBGSHRiRjRMZktiMjI4WkNvCkhmVGhxTGFBeittQ3JCMDA2K0or
        QnlVVWM0TmtQVnlUQUpyQmw4TE9ZUHMKLS0tIHc5WE5CZGZlTzdxYU5xQU5panpr
        UzU4dUM3N2hrczEvL21McC8vdGl3Y1EKfMovTvP43oC6XvgROBMhJRnvv2QfeI2L
        vbm/17gKie9pYuLnQCruNXPZQH1DkSQuHtbsk+CWtdykYkesB1MFvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-20T15:10:27Z"
  mac: ENC[AES256_GCM,data:67jEq6O7HVPQ/w0hqEX4j7l+y+pFtawDUzleQIritTDQYGwcrLNlaIeGbjJB68Sk0kaBIohU5kT0KuuUhzIe11rpiQUMfeSP2LQJSo9LfVRRy1+4VxNZL1iP9h5XQnF5HN010gJaLW0UaPeBOacUw7m3QL2IIRIJZ7XXyczw0sU=,iv:BdNl6T/7853qJzCHCbDz1JcqKRvjRcopNa8swy2gWkM=,tag:YgkeVhVzrbfAGbaiA1S/Lw==,type:str]
  encrypted_regex: password|uri
  version: 3.10.2
