apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: vaultwarden
  password: ENC[AES256_GCM,data:+ZwPKjMN9kCrhMEqvgx4UBY5FAysZ5A=,iv:dmdze+ZQ/JTwp0/bEL9x6VbmoMhqIhRNpoAnnC2ql3E=,tag:cAHxqPBq2idsj8Z9NeAz7g==,type:str]
  dbname: vaultwarden
  host: vaultwarden-pg-rw.vaultwarden-dr
  port: "5432"
  uri: ENC[AES256_GCM,data:Lfctw+dnK9KyPm4jWpQW1pL3QpFhm/qjR2f2kXEq2B6tnfsxHSTKx0bzbLqFJiHwmJf4s1DQ4enRF6lJaDOIb50ETLEyCA4Op3mSx/h/qG2l13IHWso13HZEr12Ra1pubYc=,iv:4R6FINkNBZECfURvW00Tky7PcYz8yj2PGUkABh7Jcjw=,tag:LvWuC0A7QWQBb5DQ02gloQ==,type:str]
sops:
  age:
    - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZHZSMVFZc0FqMDdFOHo3
        SW12MHRDTHczcTdwUkM3YUxXVlBvam45YnpZCndteFAwVWVhekZIcmJURzJOSU81
        NGxqZEdiQStYdFhZRmtFbThPMkRvU28KLS0tIDBSYWc2YytmKzl4Q05JRG9NSVBZ
        Y0FxTlRZbDA2c0NYK05xRE5EUUlZK2cKTqmqtooFtIuVrX7MrHMWALMZ2E/NGfXI
        6+yrF/pGztke8otuS5o3aF3ViFJd9OROAGSLAm4aPsAoaN2Xgj+QQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-20T14:37:50Z"
  mac: ENC[AES256_GCM,data:1O79voN9ohqIzSW5BLR1t2iyDbRiOBbU9HoD6BfdxrybsNF3rsPYOygECHmIKyh/F7dM2/uvroCOJIlathuFqgRFUjRzvPBgZEbxTmYJwtFlXM1VMEejOuHGDgCCSU69NSiq59mWYKuqgWgoiKCsJVDlswxCQuWfAdT7eMqAu1k=,iv:hmZhStxkPOje2V2adLXFA/TiOD5z/UVBwHBmMm6TNwk=,tag:o2LMR9tW64Ipi9XpLATq2w==,type:str]
  encrypted_regex: password|uri
  version: 3.10.2
