---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: scheduled-backup
spec:
  cluster:
    name: mood-tracker-pg
  method: plugin
  schedule: "0 0 3 * * *"
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: backup-store
spec:
  configuration:
    destinationPath: s3://246770851643-eu-central-1-homelab-cluster-storage/backups/mood-tracker/mood-tracker/
    endpointURL: https://s3.eu-central-1.amazonaws.com
    s3Credentials:
      accessKeyId:
        name: barman-aws-creds
        key: aws_access_key_id
      secretAccessKey:
        name: barman-aws-creds
        key: aws_secret_access_key
    wal:
      compression: gzip
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: backup-store-dr
spec:
  configuration:
    destinationPath: s3://246770851643-eu-central-1-homelab-cluster-storage/backups/mood-tracker/mood-tracker-dr/
    endpointURL: https://s3.eu-central-1.amazonaws.com
    s3Credentials:
      accessKeyId:
        name: barman-aws-creds
        key: aws_access_key_id
      secretAccessKey:
        name: barman-aws-creds
        key: aws_secret_access_key
    wal:
      compression: gzip