apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mood-tracker-pg
spec:
  instances: 2
  bootstrap:
#    initdb:
#      database: mood_tracker
#      owner: mood-tracker
#      secret:
#        name: pg-secret

  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: backup-store
          serverName: tandoor-pg

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backup-store-dr

  storage:
    size: 2Gi
  monitoring:
    enablePodMonitor: true
