---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: "9.2.7"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: grafana-values
      valuesKey: values.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-values
  namespace: grafana
data:
  values.yaml: |
    persistence:
      enabled: true
      size: 2G
      type: pvc
    ingress:
      enabled: true
      ingressClassName: "cloudflare-tunnel"
      hosts:
        - "grafana.twaslowski.com"

