# This is not actually included as of now, but can trigger a backup via `kubectl apply -f backup.yaml`
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: initial-backup
  namespace: vaultwarden
spec:
  cluster:
    name: vaultwarden-pg
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
