apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: base-backup
spec:
  cluster:
    name: vaultwarden-pg
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
