apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-pg
  namespace: vaultwarden
spec:
  instances: 1

  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
      secret:
        name: pg-secret

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true
