apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: postgres-cluster
      version: "0.3.3"
      sourceRef:
        kind: HelmRepository
        name: homelab
        namespace: flux-system
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: postgres-values-cm
    - kind: Secret
      name: postgres-values-secret