apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: scheduled-backup
  namespace: vaultwarden
spec:
  cluster:
    name: vaultwarden-pg
  method: plugin
  schedule: "0 */6 * * *"
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
