apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: vaultwarden
      version: "0.32.1"
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: vaultwarden-values