apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
spec:
  interval: 15m
  chart:
    spec:
      chart: k8up
      version: "4.8.4"
      sourceRef:
        kind: HelmRepository
        name: k8up-io
      interval: 15m