apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: backup
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: https://s3.eu-central-1.amazonaws.com
      bucket: 246770851643-eu-central-1-homelab-cluster-storage
      accessKeyIDSecretRef:
        name: aws-creds
        key: aws_access_key_id
      secretAccessKeySecretRef:
        name: aws-creds
        key: aws_secret_access_key