apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fluent-bit
resources:
  - namespace.yaml
  - release.yaml
  - secret.yaml
configMapGenerator:
  - name: fluent-bit-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml