apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: grafana-k8s-monitoring-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml