apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: grafana
spec:
  interval: 15m
  chart:
    spec:
      chart: k8s-monitoring
      version: "3.2.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: grafana-k8s-monitoring-values
    - kind: Secret
      name: grafana-k8s-monitoring-values