cluster:
  name: homelab
destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    url: https://prometheus-prod-24-prod-eu-west-2.grafana.net./api/prom/push
    auth:
      type: basic
      username: "2002986"
      password: ENC[AES256_GCM,data:UwJWKjz0wxQD1IwCOvb3Nxv0mDDtCZaZFg9SRwjd8RMcxi9Q3FmPuLVvymtTMFA/PCfz4cAnCI5CVNOQ/TjF/KWrvW1idBB5ig8DJZ6mdFNfWeyM9aqTAXa+89t0kR8sa7hisEgPfBkCbxZPF4rFuLksA0K3L7kJ7MFXJlAX1/R4wE6/VlBeG2DXjp1C0htW0EfJE1nYnuGSOKFW9h2p1zWSCAA1tEIQ,iv:NLpnDvHCUvRGgbwUnjyxUybUDwtERKYPzNHZhc8OpYg=,tag:QKR/MXc9aG+vAn6V1cY90Q==,type:str]
  - name: grafana-cloud-logs
    type: loki
    url: https://logs-prod-012.grafana.net./loki/api/v1/push
    auth:
      type: basic
      username: "1099748"
      password: ENC[AES256_GCM,data:7RE/ok1JbMv3qN97TAqSoMwHQwvhfaTzL4bmbWJT1GpYaoHupYgJ8bQSqL4ngYPVgeqh6RX5CGlzLPirzQFmxK56EJJ8ledcPC72mSC7cMWPAPt6+zWLOo+zan2DwzBX0lrmk/maYfFr4f9lliwOkN70WtrankremrnZFtrTq+J3ZW3gmlSo7LThk01myIvSv4XRQqqPb4OOTHjzwILYoPg0fGIqifzS,iv:+j5Ohn2pvWZW/4DMKfvd6X7dfc9Sa//XitdlgKQfJNI=,tag:skgU2YR7Nx35uha2wlgb9Q==,type:str]
  - name: grafana-cloud-otlp-endpoint
    type: otlp
    url: https://otlp-gateway-prod-eu-west-2.grafana.net./otlp
    protocol: http
    auth:
      type: basic
      username: "1141969"
      password: ENC[AES256_GCM,data:4Ub/b2wdZnFV8hglufVSeFFRuBkAdg5++zqbagPHC0ifVih71rMrWkNd1hW0yIermgcf22kn9PCh4AIMGcnQKkVRtu3JhOtJaRbEZKSBKasC4oVVCfz3weFTt5kQJ0Uo8i4hmeSsleZnW/bgYfU3N6wbEd3zBadvGiUm2batO+DyLtqb5L5HBHpaVpfU2To0HzunPMZtXDAAb6OIpDzINXpP9RuUdstn,iv:VsNzXvWO6i/UXVw6LJvnSK5WQi91wCVNcUMVLqg5GtY=,tag:KRYHoUMIfldH/4AMHX/3dQ==,type:str]
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true
clusterMetrics:
  enabled: true
clusterEvents:
  enabled: true
podLogs:
  enabled: true
applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
alloy-metrics:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-metrics-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: homelab
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-011.grafana.net
    auth:
      type: basic
      username: "1141969"
      password: ENC[AES256_GCM,data:P89nP1honBZOnGSr7iyBm47htwsyfM4RWd+NvrFavzU2MKbgAJWVCupASnXMASxNX4PN4wl15USndYugZYOnuWGCm5gXzr5ArI30W6kn2Dn1SVRoM7O6AoqlcGenpZCdlqHjLrjVU1N5kkd59b36vpOXcpiu5Xvunqj21kykC6+Wp1GuqTDcrZ5z4Ffqq0dDI9Rt/emLx9UB/Xv+Qv/m5kzGChUzS3wv,iv:O0OXzGxR/pOba4PnMboAMgCp0r5acc3K3FIB6uni5/A=,tag:U70wYdLUkzByvBN4oy+kFQ==,type:str]
alloy-singleton:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: homelab
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-011.grafana.net
    auth:
      type: basic
      username: "1141969"
      password: ENC[AES256_GCM,data:3y/SG053zx5WRPWTTsQRIZtdDo4fqiX/tkcrfunGmnIgKgvl8evB1KDh2l4ZmAPWKVCmejTztKlLWv7xs85HKpRG3MX3rPYXPfBwjYauNBiALfaTWxLMVaMdQNnjC256Jas3MkSewQE8p1bv3meKnvAyDl5kes/UHHMQIzp1Xm//5z7Kht/evyjASt9UoMmZkNgZJS6EOP3hhJ0GcywrnV38neWsYXCH,iv:u4t9oSFGYeHJeFj0X36lqicy0vdeAyTAYv24VMvjZhQ=,tag:a+z0kbg1Eh3M0/oUjqBFrQ==,type:str]
alloy-logs:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-logs-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: homelab
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-011.grafana.net
    auth:
      type: basic
      username: "1141969"
      password: ENC[AES256_GCM,data:8INxmv9KAlqinh8XP2Zx0eY1+V/ZWWFAcDXfp2E86mDI8yAvpkvXtb9uh3Cuf7wyM2ixTfwn+CectNZjzr0M8JsNXqhJYjV9MGBz8MN8QZvsXhRJpLEt8tk10x14XC78XEbYfT3k/i1bq3O10JBRopO6smHAhjzkhTgLmXx+hGRAHgzEa7CoF8ZDXH9V9wH1g/5gbTRqbPbEJWpw9L4yTC6WDgKaQxTp,iv:lyqo5OvsYB9VciKTozTTkW9oiSARo4W4CoBFJmC+amw=,tag:LhdsuK+bDAW2sG9MwJqw1A==,type:str]
alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-receiver-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: homelab
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-011.grafana.net
    auth:
      type: basic
      username: "1141969"
      password: ENC[AES256_GCM,data:blVY8lDAOQgZ8u9zVFWI0hKYkTBad31ztQW015IZXsLXQ2/CpXQgG5jYFwd3D5o1FWdX/C5Fw+5SQ0dFm0XxCNLKd9hvBNEAM9i6JCBm6yygphVKsvnqSVwYkoqO+PIlKwpZO7B5Ilmrekm437WokMbN7sr5zjX2B7dghLJhMxdNSbV4tesJdx8SGieCFegRSX5da6DB5qPrJxcL4UWYHnr9k5gDpUwu,iv:qUJzf7GKW8ttoyfy3iM0jmW3tGXhJCmXF8MDukff5kM=,tag:8KZ4PCWugRv73GgfjwwS6A==,type:str]
sops:
  age:
    - recipient: age1a5juyrapd78njp023e8hf0nmzvgwz2h47kcdvum4kh8m8ww4n9fqveqfzl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSjVRNUNVTmN4Q1FaQTFF
        S0J4ZCtGaC9NTzlaaUFHL0RUWjQ5VGdKQVRRCjRBUlB1T1VnSzdoNk5kSXBkdU5o
        dnEvUUJ6UElvWW9xVnNxV0lpeDFMb1kKLS0tIE4rWTdvbjlSTld2NzlSeEZvNnBC
        blJIVlkrTGpJTVJEemZFQnptdHpPRmMKPTTe/zwnEdxSFknkRh4YqU/gXjbPAPp5
        5oqZvHh/hufIEzZs+6qsZICN6catEtZTL/qEaQS80w0F9Ow180w4kA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-10T11:19:18Z"
  mac: ENC[AES256_GCM,data:haFj5VOLUXsUUxlO+qU2OQoDMe2lAebabAsGPX+c8hJprE045Ce0fmfTtluLVIGVkfvKaWCKcuLuDI1H2H0WXpMdd6NkQ88afBOwThHWfd1jjgdtnRDhQv0q1S/KfvaEhpWgeGv6pduNwSs3rU+50DZURiQTuo802W9QZjj3OP8=,iv:TNYDEkoyOLpnoyZYOo7FwItSgVlq58bY6TN6JcgyC3w=,tag:/2QqN0DCGnbSQQP3Dqp1Xg==,type:str]
  encrypted_regex: password
  version: 3.10.2
